/**
 * Memory feedback application — SSOT C.3.4 + D.5.1.
 *
 * Maps user-facing reaction controls to canonical signals and delegates
 * the mutation to `async/itemUpsert.ts`:
 *
 *   | Action        | Signal         | Effect (summary)                          |
 *   |---------------|----------------|-------------------------------------------|
 *   | yes_that_fits | yes_that_fits  | +0.25 confidence, confirmed_by_user,       |
 *   |               |                | may upgrade hypothesis→confirmed_insight   |
 *   | not_quite     | not_quite      | -0.15 confidence, status→re_check,         |
 *   |               |                | rejected_by_user                           |
 *   | not_anymore   | not_anymore    | status→stale, marked_stale_by_user         |
 *   | hide          | hide           | visibility_scope→hidden (no truth change)  |
 *
 * This module is async-friendly: the pure path builds the new state,
 * the persist path writes item + audit through `StorageAdapter` in a
 * single atomic call (contract in `adapters/storage.ts`).
 */

import type { StorageAdapter } from "../adapters/storage";
import type { TelemetryAdapter } from "../adapters/telemetry";
import {
  applySignalToItem,
  persistSignalToItem,
  type ApplySignalParams,
  type ApplySignalResult,
} from "../async/itemUpsert";
import type { SignalId } from "../state/signalRegistry";
import { newUuid } from "../async/id";
import type {
  ContextSurface,
  MemoryItem,
  SourceType,
} from "../types";

export type MemoryFeedbackAction =
  | "yes_that_fits"
  | "not_quite"
  | "not_anymore"
  | "hide";

const ACTION_SIGNAL: Record<MemoryFeedbackAction, SignalId> = {
  yes_that_fits: "yes_that_fits",
  not_quite: "not_quite",
  not_anymore: "not_anymore",
  hide: "hide",
};

export interface ApplyFeedbackParams {
  item: MemoryItem;
  action: MemoryFeedbackAction;
  now: Date;
  /** Where in the UI the action was triggered (SSOT C.3.4). */
  context_surface?: ContextSurface;
  /**
   * Source type on the item's `sources[]` entry. Defaults to
   * `memory_screen` per C.3.4 which is where reaction controls live.
   */
  source_type?: SourceType;
  /** Stable event id for idempotency; autogenerated when omitted. */
  source_event_id?: string;
  /** Pass-through for `applySignalToItem.prior_signals` (tests). */
  prior_signals?: ApplySignalParams["prior_signals"];
}

export function buildApplyParams(
  params: ApplyFeedbackParams,
): ApplySignalParams {
  return {
    item: params.item,
    signal_id: ACTION_SIGNAL[params.action],
    now: params.now,
    source_event_id: params.source_event_id ?? newUuid(),
    source_type: params.source_type ?? "memory_screen",
    context_surface: params.context_surface ?? "memory_screen",
    session_id: null,
    prior_signals: params.prior_signals,
  };
}

export function applyFeedback(
  params: ApplyFeedbackParams,
): ApplySignalResult {
  return applySignalToItem(buildApplyParams(params));
}

export interface PersistFeedbackOptions {
  storage: StorageAdapter;
  telemetry?: TelemetryAdapter;
}

export async function persistFeedback(
  opts: PersistFeedbackOptions,
  params: ApplyFeedbackParams,
): Promise<ApplySignalResult> {
  const applyParams = buildApplyParams(params);
  const result = await persistSignalToItem(opts.storage, applyParams);

  opts.telemetry?.capture("memory_feedback_submitted", {
    user_id: params.item.user_id,
    memory_item_id: params.item.id,
    action: params.action,
    signal_id: applyParams.signal_id,
    transition: result.transition,
    applied_delta: result.applied_delta,
    prev_status: params.item.status,
    next_status: result.item.status,
    context_surface: applyParams.context_surface,
    timestamp: params.now.toISOString(),
  });

  return result;
}
