/**
 * Downloadable Ukrainian guide for interpreting MindJar memory debug exports.
 *
 * This file intentionally contains prose, not runtime logic. It should stay
 * close to the implementation and SSOT so a user can export it together with
 * raw debug data and paste both into another AI/chat for analysis.
 */

export function buildMemoryImplementationContextText(exportedAt: string): string {
  return [
    "# MindJar Memory Layer — контекст реалізації для аналізу debug export",
    "",
    `exported_at: ${exportedAt}`,
    "призначення: цей файл треба вставляти поруч із memory debug export або completed-practice debug export, щоб інший агент міг правильно інтерпретувати всі поля, ключі, before/after зміни та відповідність SSOT.",
    "джерело істини: docs/2026/MindJar_consolidated_documentation_system_19_04_2026_03-16.md",
    "реалізація: mindjar-dashboard/src/lib/memory/* + mindjar-dashboard/src/app/dashboard/ai-test/page.tsx",
    "",
    "## 1. Головний принцип",
    "",
    "MindJar memory — local-first. У dashboard simulator canonical memory state зберігається через StorageAdapter у browser localStorage. Серверні AI calls можуть отримувати контекст і повертати результат, але server traces не є canonical durable memory.",
    "",
    "AI не має отримувати всю історію користувача. Для конкретної задачі AI отримує короткий релевантний контекст, який обирається retrieval-логікою: stable profile subset, recent summaries, top relevant memory items, current session card, confidence level, avoided topics і safety context.",
    "",
    "Raw storage dump потрібен для debugging. Для продуктового AI-context правильним джерелом є canonical retrieval, а не прямий snapshot localStorage.",
    "",
    "## 2. Canonical runtime pipeline",
    "",
    "Канонічний шлях для user action:",
    "",
    "1. User action: check-in / journal / reflection / self-discovery / practice.",
    "2. Normalization: вхідні UI дані перетворюються на SessionCard.",
    "3. saveSessionCard: SessionCard зберігається у StorageAdapter.",
    "4. buildSessionSummaryV1Sync: створюється мінімальний sync summary.",
    "5. saveSessionSummary: summary зберігається локально.",
    "6. Sync memory updates: для check-in selected triggers можуть створити/reinforce observation.",
    "7. Retrieval: useSmartSummary() викликає retrieve() і бере релевантні memory items за surface rules.",
    "8. Smart Summary generation: AI отримує current session + relevant memory context.",
    "9. Safety classifier: кожен output проходить safety gate.",
    "10. UI output: advice / insight / affirmation / optional summary.",
    "11. Feedback/audit: user feedback може створити audit event або змінити item state.",
    "",
    "У ai-test canonical flow використовується для check-in, journaling, self-discovery і reflection. Старий шлях, де сторінка напряму будувала memory_context з localStorage для prompt, не є основним шляхом.",
    "",
    "## 3. Як читати memory debug export",
    "",
    "Raw memory debug export має такі секції:",
    "",
    "- metadata: технічна інформація про експорт.",
    "  - exported_at: ISO timestamp, коли файл скачали.",
    "  - user_id: sim user id, для якого зібрано state.",
    "",
    "- stable_profile: derived profile, який AI surfaces використовують як compact personalization context.",
    "  - Це не primary canonical storage. Він похідний від memory items/session activity.",
    "  - Може бути трохи stale між sync submit і async enrichment.",
    "",
    "- recent_summaries: останні SessionSummaryV1Sync rows.",
    "  - Це коротка історія сесій, яку можна давати AI без повної raw history.",
    "",
    "- memory_items: raw MemoryItem rows.",
    "  - Це canonical state model для claims/preferences/observations/hypotheses.",
    "",
    "- telemetry_tail: останні локальні telemetry records.",
    "  - Це observability/debug layer, не memory truth.",
    "",
    "- storage_dump: повний snapshot StorageAdapter.",
    "  - Містить session_cards, summaries_v1, memory_items, memory_audits, safety_events, stable_profile, daily_snapshots тощо.",
    "  - Використовувати для діагностики persistence. Для логічного аналізу спершу дивитись canonical sections вище.",
    "",
    "## 4. Як читати completed-practice debug export",
    "",
    "Completed practice export зберігає не тільки AI response, а весь debug package для практики:",
    "",
    "- practice_input: те, що користувач/тестер ввів у UI.",
    "  - Для check-in: mood, emotions, tags, note.",
    "  - Для journaling: selectedPractice, journalAnswers, userText.",
    "  - Для self-discovery: selectedPractice, quizTrait, answers, userText.",
    "  - Для reflection: selectedReflection, chatMessages, chat pairs, feedback, userText.",
    "",
    "- memory_request: exact object, який було передано в submitSession() або submitReflection().",
    "  - Це найкраще місце, щоб перевірити session_type mapping, user_id, selected_triggers, user_stated_text, practice_specific.",
    "",
    "- memory_before: snapshot memory state безпосередньо перед submit.",
    "  - Порівнюється з memory_after.",
    "",
    "- memory_result: return value з memory hook.",
    "  - Для useSessionSubmit(): session_card, v1_summary, smart_summary.",
    "  - Для useReflectionSubmit(): session, reinforced_items, signal_results.",
    "",
    "- memory_after: snapshot memory state після submit.",
    "  - Тут видно нову summary, нові/reinforced items, activity_snapshot, telemetry changes.",
    "",
    "- ai_response: те, що показав UI.",
    "  - Зазвичай це compact wrapper навколо smart_summary.output + raw_session_result.",
    "",
    "## 5. MemoryItem — всі ключові поля",
    "",
    "MemoryItem — canonical row у state model. Status — lifecycle state. stale не є type, stale є status.",
    "",
    "- id",
    "  - Унікальний id memory item.",
    "  - Має лишатися стабільним між updates того самого item.",
    "",
    "- user_id",
    "  - Власник item.",
    "  - Має збігатися з debug export metadata.user_id / memory_request.user_id.",
    "",
    "- type",
    "  - immutable_fact | declared_preference | temporary_constraint | declared_boundary | observation | hypothesis | confirmed_insight.",
    "  - Визначає lifecycle, copy softness, decay/freshness і чи може item показуватися користувачу.",
    "",
    "- status",
    "  - active: item живий і може брати участь у retrieval/projection.",
    "  - re_check: item потребує повторної перевірки після soft rejection/contradiction.",
    "  - stale: item застарів або користувач сказав not_anymore.",
    "  - removed_by_user: user-removed/hidden item; не має показуватися як активна пам'ять.",
    "",
    "- statement_user_facing",
    "  - Текст, який можна показати у Memory screen.",
    "  - Для weak/inferred items має бути м'який: Possibly / It seems / I'm noticing.",
    "  - Не має звучати як diagnosis або жорстке твердження.",
    "",
    "- statement_internal",
    "  - Internal claim identifier, часто key=value або observation_theme=...",
    "  - Може бути менш user-friendly, використовується для audit/debug.",
    "",
    "- content",
    "  - Нормалізоване semantic ядро item.",
    "  - content.claim: коротка claim-форма.",
    "  - content.domain: identity | preference | boundary | context | behavior | emotion | support.",
    "  - content.polarity: positive | negative | neutral | mixed.",
    "  - content.intensity: 0..1 сила/насиченість змісту. Це не truth confidence.",
    "",
    "- internal_evidence_summary",
    "  - Optional evidence note.",
    "  - За замовчуванням не user-facing.",
    "",
    "- confidence",
    "  - Base truth confidence 0..1.",
    "  - Приклади: onboarding direct answer стартує з 0.85; selected trigger observation може стартувати з 0.25.",
    "  - Confidence не дорівнює visibility. Low-confidence item може існувати в raw debug, але не показуватись у user-facing projection.",
    "",
    "- freshness_score",
    "  - 0..1 score актуальності з урахуванням decay.",
    "  - Залежить від type і last_supported_at.",
    "",
    "- active_confidence",
    "  - confidence * freshness_score.",
    "  - У retrieval має recompute-итися, cached value не є остаточним source of truth.",
    "  - Використовується для thresholds, ordering і relevance score.",
    "",
    "- last_confidence_computed_at",
    "  - Коли востаннє було оновлено cached freshness/active_confidence.",
    "",
    "- first_seen_at",
    "  - Коли claim вперше з'явився.",
    "",
    "- last_supported_at",
    "  - Коли claim востаннє отримав corroboration/support.",
    "  - Важливо для decay.",
    "",
    "- user_feedback_state",
    "  - none: user ще не реагував явно.",
    "  - confirmed_by_user: user підтвердив.",
    "  - rejected_by_user: user soft-rejected.",
    "  - marked_stale_by_user: user сказав, що вже неактуально.",
    "",
    "- sources",
    "  - Масив evidence sources.",
    "  - Кожен source має:",
    "    - source_type: onboarding | check_in_text | trigger_tags | reflection | journal | self_discovery | practice_feedback | pattern_detection | echo_save | memory_screen.",
    "    - source_event_id: id події/session, яка дала signal.",
    "    - session_id: session id або null.",
    "    - timestamp: ISO час signal.",
    "    - weight: signal strength / contribution.",
    "    - signal_kind: declaration | corroboration | resonance | contradiction | truth_confirmation.",
    "",
    "- source_event_ids",
    "  - Deduped список source_event_id для швидкого audit/debug.",
    "",
    "- sensitivity_level",
    "  - public: без особливої чутливості.",
    "  - personal: персональна інформація.",
    "  - sensitive: чутливий контекст, boundary, avoid topic, тощо.",
    "  - avoided_adjacent: тема поруч із avoided topic; треба бути обережним.",
    "",
    "- visibility_scope",
    "  - memory_screen: можна показати у Your Personalization, якщо проходить інші gates.",
    "  - summary: можна використати для summary context.",
    "  - plan_context: можна використати для plan/recommendations.",
    "  - hidden: не показувати user-facing.",
    "",
    "- theme_tags",
    "  - Tags для retrieval, clustering, matching.",
    "  - Наприклад theme:work, focus:stress, boundary:body_appearance.",
    "",
    "- related_focus_areas",
    "  - Focus areas, з якими пов'язаний item.",
    "  - Дає bonus у intent matching.",
    "",
    "- state_history",
    "  - Lifecycle transitions.",
    "  - Кожен запис має from_status, to_status, trigger_event_id, timestamp, auto_or_manual.",
    "",
    "- supersedes_id",
    "  - id старого item, який цей item замінює.",
    "",
    "- version",
    "  - Increment на update item.",
    "",
    "- created_at / updated_at",
    "  - Час створення і останнього оновлення row.",
    "",
    "## 6. Memory item types",
    "",
    "- immutable_fact",
    "  - Explicit durable fact від user declaration.",
    "  - Приклад: ім'я користувача.",
    "",
    "- declared_preference",
    "  - Пряма declared preference.",
    "  - Приклади: focus area, support style, realistic action mode, timing preference.",
    "",
    "- temporary_constraint",
    "  - Поточний контекст, який має decay швидше.",
    "  - Приклад: зараз важко зі stress/sleep/workload.",
    "",
    "- declared_boundary",
    "  - User-declared boundary / avoided topic.",
    "  - Має бути доступний для safety/retrieval.",
    "  - У current implementation onboarding boundaries мають visibility_scope memory_screen, щоб user міг їх бачити й коригувати.",
    "",
    "- observation",
    "  - Weak recent pattern.",
    "  - Може зберігатися в raw debug з confidence 0.25.",
    "  - Не має показуватися user-facing, якщо confidence < 0.4.",
    "",
    "- hypothesis",
    "  - Inferred pattern, який потребує corroboration.",
    "  - User-facing copy має бути soft.",
    "",
    "- confirmed_insight",
    "  - Високодостовірний insight.",
    "  - Може з'явитися тільки через truth-confirmation path, не через like/regenerate/echo save.",
    "",
    "## 7. Evidence source registry і signal semantics",
    "",
    "- onboarding",
    "  - Explicit declaration.",
    "  - base_confidence = 0.85.",
    "  - Може створити immutable_fact / declared_preference / declared_boundary.",
    "",
    "- check_in_text",
    "  - User typed free text у check-in.",
    "  - +0.15 evidence.",
    "  - Підтримує observation/hypothesis, але не confirmed_insight alone.",
    "",
    "- trigger_tags",
    "  - Structured selected triggers/tags.",
    "  - +0.10 evidence.",
    "  - Supports observation only.",
    "  - Якщо user не писав текст, observation source не має бути check_in_text.",
    "",
    "- reflection",
    "  - Deeper explicit reflection text.",
    "  - +0.20 evidence.",
    "  - Can support hypothesis через D.2 rules.",
    "",
    "- journal",
    "  - Weak single-source journal signal.",
    "  - +0.10 evidence.",
    "  - Не створює truth alone. SSOT: мінімум 3 journal entries на тему + достатні weights для hypothesis.",
    "",
    "- self_discovery",
    "  - Completion: engagement signal, truth delta 0.",
    "  - Interpretation: weak thematic hypothesis, base_confidence 0.25.",
    "  - Не має мовчки ставати confirmed_insight.",
    "",
    "- practice_feedback",
    "  - Explicit Better/Worse після practice.",
    "  - Better: corroboration support.",
    "  - Worse: contradiction path.",
    "",
    "- pattern_detection",
    "  - Async/system-inferred pattern.",
    "  - Треба перевіряти confidence і sources.",
    "",
    "- echo_save",
    "  - Resonance signal.",
    "  - Не truth confirmation.",
    "",
    "- memory_screen",
    "  - Direct user correction/confirmation/hide у Memory screen.",
    "  - Найважливіший шлях для user-controlled corrections.",
    "",
    "signal_kind:",
    "- declaration: user прямо заявив.",
    "- corroboration: signal підтримує можливий pattern.",
    "- resonance: style/format preference, не truth.",
    "- contradiction: signal суперечить item.",
    "- truth_confirmation: user прямо підтвердив true/fit.",
    "",
    "## 8. StableProfile — всі ключі",
    "",
    "stable_profile — derived runtime view над memory items/session state. Він допомагає AI surfaces отримувати compact personalization context.",
    "",
    "- user_id: власник profile.",
    "- basics.name: ім'я, якщо user його declared.",
    "- basics.timezone: timezone, якщо доступний.",
    "- basics.locale: locale, якщо доступний.",
    "- declared.primary_motivation: motivations з onboarding.",
    "- declared.top_value: top/first primary motivation.",
    "- declared.focus_areas: explicit focus areas.",
    "- declared.support_style: preferred interaction style.",
    "- declared.realistic_action_modes: які дії user готовий пробувати.",
    "- declared.daily_time_budget: preferred session duration.",
    "- declared.support_timing_preference: коли підтримка краще заходить.",
    "- current_constraints.pain_map: поточні важкі сфери.",
    "- current_constraints.avoided_topics: теми, з якими AI має бути обережним або уникати.",
    "- current_constraints.current_life_context[].topic: активний contextual topic.",
    "- current_constraints.current_life_context[].active_until: optional expiry.",
    "- what_tends_to_help[].practice_type: тип practice.",
    "- what_tends_to_help[].effectiveness_score: derived help score.",
    "- what_tends_to_help[].sample_size: скільки samples підтримує цей score.",
    "- active_hypotheses[].id: linked memory item id.",
    "- active_hypotheses[].statement: short statement.",
    "- active_hypotheses[].confidence: confidence.",
    "- active_hypotheses[].theme: theme.",
    "- confirmed_insights[]: така сама структура, але тільки confirmed items.",
    "- confidence_level: A | B | C | D.",
    "- user_confidence_score: aggregate 0..1.",
    "- last_refreshed_at: коли profile оновили.",
    "- activity_snapshot.total_sessions: кількість stored session summaries.",
    "- activity_snapshot.days_active_in_last_14: active days за 14 днів.",
    "- activity_snapshot.text_sessions_ratio: ratio sessions з user_stated text.",
    "- activity_snapshot.streak_status: active | broken | none.",
    "",
    "## 9. Confidence levels",
    "",
    "- Level A — Exploring.",
    "  - Score низький або total_sessions < 2.",
    "  - AI має уникати claims, більше питати, не робити персональних висновків.",
    "",
    "- Level B — Learning.",
    "  - Pattern may be emerging.",
    "  - Потрібні softeners.",
    "",
    "- Level C — Understanding.",
    "  - Можна говорити конкретніше, якщо grounded in signals.",
    "",
    "- Level D — Deepening.",
    "  - Дозволені direct warm assertions, якщо backed by confirmed insights.",
    "",
    "## 10. SessionCard — всі ключі",
    "",
    "SessionCard — canonical normalized event unit.",
    "",
    "- session_id: unique session id.",
    "- user_id: owner.",
    "- session_type: check_in | quick_check_in | journal | reflection | breathing | meditation | self_discovery | personal_practice.",
    "- started_at: ISO start.",
    "- completed_at: ISO completion.",
    "- entry_mood: great | good | okay/ok | bad | awful | null.",
    "- exit_mood: mood після practice, якщо applicable; часто null.",
    "- user_stated_text: normalized free text. Це ключовий text signal для AI/memory.",
    "- selected_emotions[]: structured emotions.",
    "  - tKey: localization key.",
    "  - label: displayed label.",
    "  - icon/moodDependencies/isCustom/isAI/isVisible: optional UI metadata.",
    "- selected_triggers[]: structured context tags.",
    "  - tKey: localization key.",
    "  - label: displayed label.",
    "  - categoryId: trigger category.",
    "  - icon/isCustom/isAI: optional metadata.",
    "- completion_state: completed | abandoned | timed_out.",
    "- reaction_to_output.liked: user liked AI output. Resonance only.",
    "- reaction_to_output.disliked: user disliked AI output. Resonance only.",
    "- reaction_to_output.echo_saved: user saved/echoed output. Resonance only.",
    "- reaction_to_output.regenerated: user requested another version. Resonance only.",
    "- practice_specific.practice_id: id of journal/quiz/practice/reflection prompt.",
    "- practice_specific.effectiveness_self_report: explicit helped/worse/same-like report if available.",
    "- practice_specific.duration_seconds: duration if known.",
    "- flags_initial: initial flags, usually ['none'].",
    "- client_metadata: platform/app/simulator metadata.",
    "",
    "Canonical mapping in ai-test:",
    "- mood -> check_in або quick_check_in.",
    "- journaling -> journal.",
    "- reflection -> reflection.",
    "- question -> self_discovery.",
    "",
    "## 11. SessionSummaryV1Sync — всі ключі",
    "",
    "SessionSummaryV1Sync — immediate sync summary, яка використовується як recent context.",
    "",
    "- session_id: linked SessionCard id.",
    "- user_id: owner.",
    "- session_type: copied canonical session type.",
    "- completed_at: session completion time.",
    "- user_stated: array of normalized user text snippets.",
    "- emotional_tone.primary: coarse primary mood/emotion.",
    "- emotional_tone.valence: positive | neutral | negative | mixed-like valence.",
    "- themes_obvious: obvious themes from selected_triggers/user text.",
    "- helped_or_not: explicit practice feedback if known; source of truth is user report.",
    "- summary_version: v1_sync.",
    "",
    "## 12. MemoryAuditEvent — як читати",
    "",
    "Audit event фіксує зміну item окремо від самого item.",
    "",
    "- event_id: unique audit id.",
    "- memory_item_id: item, який змінився.",
    "- action: confirm | soft_reject | mark_stale | hide | why_query | correction.",
    "- user_id: owner.",
    "- timestamp: when audit happened.",
    "- previous_state: confidence/status/user_feedback_state/visibility_scope before.",
    "- new_state: state after.",
    "- context_surface: memory_screen | smart_summary | reflection | plan | weekly_summary.",
    "- source_event_id: parent session/event id або null.",
    "",
    "## 13. Retrieval",
    "",
    "Retrieval відповідає за те, які memory items потрапляють в AI context.",
    "",
    "Universal ranking uses:",
    "- active_confidence: strongest signal of item usefulness now.",
    "- intent_match_score: match between item.theme_tags / related_focus_areas and current intent.",
    "- recency_score: newer/recently supported items rank higher.",
    "- source_reliability: onboarding/memory_screen > check_in/reflection > weak/system signals.",
    "- user_feedback_boost: confirmed user feedback boosts relevance.",
    "",
    "Surface rules:",
    "- smart_summary_post_checkin: excludes raw low-confidence hypotheses/items below threshold; sensitive items blocked unless session mention override applies.",
    "- chat_reply: excludes contradictory unresolved items.",
    "- weekly_summary: stricter sensitivity filtering.",
    "- self_discovery_go_deeper: limited context budget.",
    "- plan_context: declared preferences/boundaries/facts/confirmed insight/temporary constraints.",
    "- memory_screen: user-facing projection; stale/hidden removed; confidence < 0.4 observations hidden by projection.",
    "",
    "Low-confidence fallback:",
    "- Якщо sum(active_confidence) нижче threshold, AI має використовувати exploratory tone і не робити memory claims.",
    "",
    "## 14. Smart Summary output",
    "",
    "- advice: конкретна маленька дія, бажано <5 хв.",
    "- insight: grounded synthesis. Має reference specific signal.",
    "- affirmation: завжди first-person I-form, ні в якому разі не 'you are...'. Приклади: 'I can handle this', 'I deserve compassion'.",
    "- summary: optional 2-3 sentence synthesis.",
    "- references_used: short references grounded in input.",
    "- word_count: word count of output.",
    "- safety_flag: none | soft | hard | critical.",
    "",
    "Rules:",
    "- Must reference user_stated, selected_emotions або focus_areas.",
    "- No generic lines that could fit any random user.",
    "- Respect avoided_topics.",
    "- Respect confidence_level.",
    "- Safety classifier pass before show.",
    "",
    "## 15. Safety classifier",
    "",
    "- flag: none | soft | hard | critical.",
    "- reason: why classifier chose the flag.",
    "- suggested_action: regenerate | safe_template | crisis_flow | manual_review.",
    "- classifier_latency_ms: actual latency.",
    "- timestamp: classifier timestamp.",
    "- output_hash: hash of checked output.",
    "",
    "Expected behavior:",
    "- none: output can be shown.",
    "- soft: regenerate.",
    "- hard: safe_template або manual_review.",
    "- critical: crisis_flow.",
    "- classifier timeout: safe template for session + classifier_timeout logging.",
    "",
    "Telemetry:",
    "- safety_classifier_completed: classifier ran, including flag none.",
    "- safety_flag_raised: only for soft/hard/critical, not for none.",
    "",
    "## 16. Completed practice debug analysis checklist",
    "",
    "1. Перевірити, що memory_request.user_id збігається з metadata.user_id.",
    "2. Перевірити session_type mapping.",
    "3. Перевірити user_stated_text: чи не пустий там, де потрібен text signal.",
    "4. Перевірити selected_triggers: чи вони структурні, не вигадані, чи мають labels.",
    "5. Порівняти memory_before.summaries і memory_after.summaries: має додатися нова summary.",
    "6. Порівняти memory_before.stableProfile.activity_snapshot і memory_after.stableProfile.activity_snapshot.",
    "7. Порівняти memory_before.items і memory_after.items.",
    "8. Якщо створено observation із selected trigger, source_type має бути trigger_tags.",
    "9. Якщо створено item із free text, source_type має відповідати check_in_text / reflection / journal.",
    "10. Перевірити, що слабкі signals не створили confirmed_insight.",
    "11. Перевірити smart_summary.output.references_used: чи grounded in input.",
    "12. Перевірити affirmation: first-person I-form.",
    "13. Перевірити telemetry_tail: session_completed, smart_summary_viewed, safety_classifier_completed.",
    "14. Перевірити, що safety_flag_raised не з'явився для flag none.",
    "15. Перевірити, що low-confidence observations не показуються в user-facing Memory screen.",
    "",
    "## 17. Common red flags",
    "",
    "- source_type check_in_text, коли user_stated_text пустий і був тільки selected trigger.",
    "- confidence низький, але UI/AI говорить як про факт.",
    "- self_discovery result одразу стає confirmed_insight.",
    "- journal entry alone створює strong truth claim.",
    "- safety_flag_raised з flag none.",
    "- affirmation у second person: 'You are...', 'You're...'.",
    "- stable_profile.activity_snapshot.total_sessions не росте після session submit.",
    "- memory_request.user_id не збігається з debug user_id.",
    "- raw storage_dump суперечить canonical sections.",
    "",
    "## 18. Поточні implementation notes",
    "",
    "- buildOnboardingItems() створює onboarding-derived memory items і audit events.",
    "- useOnboardingSubmit() persist-ить item+audit і merge-ить stable_profile.",
    "- useSessionSubmit() є canonical submit hook для check-in/journal/self-discovery.",
    "- useReflectionSubmit() використовує useSessionSubmit() і додає reflection_text signals до relevant items.",
    "- useSmartSummary() робить canonical retrieval через retrieve().",
    "- ai-test completed practice history зберігає practiceInput, memoryRequest, memoryBefore, memoryResult, memoryAfter, aiResponse.",
    "- Memory debug Download .txt — raw state export.",
    "- Memory debug Download context .txt — цей explanatory guide.",
    "",
  ].join("\n");
}

